var MixpanelLib=function(l,m){function j(a){if(!a)return!1;var b=Object.prototype.toString.call(a);return b==="[object Array]"||b==="[object HTMLCollection]"||b==="[object NodeList]"||typeof a.jquery!=="undefined"&&typeof a.length!=="undefined"||typeof a.length==="number"&&typeof a.item==="function"||typeof a.length==="number"&&typeof a.item==="string"||typeof a.length==="number"&&typeof a.item==="object"}function t(a){if(!a)return!1;return a.charAt(0)==="."||a.charAt(0)==="#"}function u(a){if(!a)return{type:"error",
query:""};var b=a.charAt(0),b=b==="."?"class":b==="#"?"id":"error";return{type:b,query:b==="error"?"":a.slice(1)}}function q(a){var b,c=0,d=[];if(a===null||a===void 0)return[];try{return Array.prototype.slice.call(a,0)}catch(f){if(typeof a.length==="number")for(b=a.length;c<b;c++)d[c]=a[c];else for(;a[c]!==void 0;)d[c]=a[c],c++;return d}}function v(a){if(typeof document.getElementsByClassName==="undefined"){var b=RegExp("(?:^|\\s)"+a+"(?:$|\\s)"),c=document.getElementsByTagName("*"),d=[],f,h;for(h=
0;(f=c[h])!=null;h++){var g=f.className;g&&g.indexOf(a)!=-1&&b.test(g)&&d.push(f)}return d}else return a=document.getElementsByClassName(a),q(a)}function w(a){if(typeof a!=="string")return a;if(document.getElementById===void 0){if(document.all!==void 0)return document.all[a];if(document.layers!==void 0)return document.layers[a];return null}else return document.getElementById(a)}function r(a,b,c){if(a!==void 0&&a!==null&&typeof b==="string"){var d=a[b]?a[b]:function(){};a[b]=function(a){d(a);return c(a)}}}
function x(a){if(a=a||window.event)a.returnValue=!1,a.preventDefault!==void 0&&a.preventDefault();return!1}function B(a,b,c,d){var a=u(a),f=null;if(a.type==="class")f=v(a.query);else if(a.type==="id")a=w(a.query),f=a!==null?[a]:[];else return!1;return y(f,b,c,d)}function z(a,e,c,d){r(a,"onclick",function(f){var h=!1,g=window.setTimeout(function(){h||(h=!0,d(!1))},b.config.track_links_timeout);if(typeof c.url==="undefined"&&a.href)c.url=a.href;b.track(e,c,function(){h||(h=!0,window.clearTimeout(g),
d(!0))});return x(f)})}function y(a,b,c,d){function f(a){return function(b){d&&d(b)===!1||a.href!==void 0&&a.href!==null&&setTimeout(function(){window.location=a.href},0)}}if(!b)return n.error("No event name provided to mpmetrics.track_links"),!1;var c=c||{},h;for(h=0;h<a.length;h++){var g=a[h];if(typeof g!=="object"||typeof g.nodeName==="undefined")return n.error("Invalid element provided to track_links:",g),!1;z(g,b,c,f(g))}return!0}function o(){if(!p){p=!0;document.removeEventListener&&(document.removeEventListener("DOMContentLoaded",
o,!1),document.removeEventListener("load",o,!1));for(;s.length>0;){var a=s.shift();b[a[0]].apply(b,a.slice(1))}}}var b={},A=!1,p=!1,s=[];b.config={cross_subdomain_cookie:!0,cookie_name:"mp_super_properties",test:!1,store_google:!1,debug:!1,track_links_timeout:300};b.jsonp_callback=function(){};b.super_properties={all:{},events:{},funnels:{}};b.funnels={};var n={log:function(){typeof window.console!=="undefined"&&window.console&&b.config.debug&&window.console.log.apply(window.console,arguments)},error:function(){typeof window.console!==
"undefined"&&window.console&&b.config.debug&&window.console.error.apply(window.console,arguments)}};b.send_request=function(a,e){if(b.config.test)e.test=1;e._=(new Date).getTime().toString();a+="?"+b.http_build_query(e);var c=document.createElement("script");c.setAttribute("src",a);c.setAttribute("type","text/javascript");var d=document.getElementsByTagName("head")[0]||document.documentElement;d.insertBefore(c,d.firstChild)};b.get_query_param=function(a,b){var b=b.replace(/[\[]/,"\\[").replace(/[\]]/,
"\\]"),c=RegExp("[\\?&]"+b+"=([^&#]*)").exec(a);return c===null||c&&typeof c[1]!=="string"&&c[1].length?"":unescape(c[1]).replace(/\+/g," ")};b.track_funnel=function(a,e,c,d,f){d=d||{};d.funnel=a;d.step=parseInt(e,10);d.goal=c;b.track("mp_funnel",d,f,"funnels")};b.track_links=function(){if(!p)return s.push(["track_links"].concat(q(arguments))),!0;var a=arguments.length>0?arguments[0]:void 0;if(a===void 0)n.error("Invalid arguments for track_links:",arguments);else if(typeof a==="string"&&t(a))return B.apply(this,
arguments);else if(j(a))return arguments[0]=q(a),y.apply(this,arguments);else n.error("Invalid arguments for track_links:",arguments);return!1};b.track=function(a,e,c,d){if(a){b.load_super_once();d=d||"events";e=e||{};e.token=e.token||b.token;var f=Math.floor(Math.random()*1E4),h=b.callback_fn;c!==void 0&&(b.jsonp_callback[""+f]=c,h+='["'+f+'"]');e.time=b.get_unixtime();b.save_campaign_params();b.save_search_keyword(document.referrer);var g;if(d!="all")for(g in b.super_properties[d])e.hasOwnProperty(g)||
(e[g]=b.super_properties[d][g]);if(b.super_properties.all)for(g in b.super_properties.all)e.hasOwnProperty(g)||(e[g]=b.super_properties.all[g]);c={event:a,properties:e};d=b.base64_encode(b.json_encode(c));b.config.debug&&(n.log("-------------- REQUEST --------------"),n.log(c));b.send_request(b.api_host+"/track/",{data:d,ip:1,callback:h});b.track_predefined_funnels(a,e)}else n.error("No event name provided to mpmetrics.track")};b.track_pageview=function(){b.track("mp_page_view",b.get_pageview_info())};
b.identify=function(a){b.register_once({distinct_id:a},"all",null,30)};b.register_once=function(a,e,c,d){b.load_super_once();e=e||"all";a===void 0&&(a={});c===void 0&&(c="None");d===void 0&&(d=7);var f;if(b.super_properties.hasOwnProperty(e))for(f in a)if(a.hasOwnProperty(f)&&(!b.super_properties[e][f]||b.super_properties[e][f]==c))b.super_properties[e][f]=a[f];b.config.cross_subdomain_cookie&&b.clear_old_cookie();b.set_cookie(b.config.cookie_name,b.json_encode(b.super_properties),d,b.config.cross_subdomain_cookie)};
b.register=function(a,e,c){b.load_super_once();e=e||"all";a===void 0&&(a={});c===void 0&&(c=7);var d;if(b.super_properties.hasOwnProperty(e))for(d in a)a.hasOwnProperty(d)&&(b.super_properties[e][d]=a[d]);b.config.cross_subdomain_cookie&&b.clear_old_cookie();b.set_cookie(b.config.cookie_name,b.json_encode(b.super_properties),c,b.config.cross_subdomain_cookie)};b.http_build_query=function(a,b){var c,d,f,h=[];b||(b="&");for(c in a)a.hasOwnProperty(c)&&(d=encodeURIComponent(a[c].toString()),f=encodeURIComponent(c),
h[h.length]=f+"="+d);return h.join(b)};b.get_unixtime=function(){return parseInt((new Date).getTime().toString().substring(0,10),10)};b.json_encode=function(a){var b=function(a){var b=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,c={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};b.lastIndex=0;return b.test(a)?'"'+a.replace(b,function(a){var b=c[a];return typeof b==="string"?b:"\\u"+
("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'},c=function(a,f){var h="",g=0,i=g="",i=0,l=h,j=[],k=f[a];k&&typeof k==="object"&&typeof k.toJSON==="function"&&(k=k.toJSON(a));switch(typeof k){case "string":return b(k);case "number":return isFinite(k)?String(k):"null";case "boolean":case "null":return String(k);case "object":if(!k)return"null";h+="    ";j=[];if(Object.prototype.toString.apply(k)==="[object Array]"){i=k.length;for(g=0;g<i;g+=1)j[g]=c(g,k)||"null";return i=j.length===
0?"[]":h?"[\n"+h+j.join(",\n"+h)+"\n"+l+"]":"["+j.join(",")+"]"}for(g in k)Object.hasOwnProperty.call(k,g)&&(i=c(g,k))&&j.push(b(g)+(h?": ":":")+i);return i=j.length===0?"{}":h?"{"+j.join(",")+""+l+"}":"{"+j.join(",")+"}"}};return c("",{"":a})};b.base64_encode=function(a){var e,c,d,f,h=0,g=0,i="",i=[];if(!a)return a;a=b.utf8_encode(a+"");do e=a.charCodeAt(h++),c=a.charCodeAt(h++),d=a.charCodeAt(h++),f=e<<16|c<<8|d,e=f>>18&63,c=f>>12&63,d=f>>6&63,f&=63,i[g++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(e)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(d)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(f);while(h<a.length);i=i.join("");switch(a.length%3){case 1:i=i.slice(0,-2)+"==";break;case 2:i=i.slice(0,-1)+"="}return i};b.utf8_encode=function(a){var a=(a+"").replace(/\r\n/g,"\n").replace(/\r/g,"\n"),b="",c,d,f=0,h;c=d=0;f=a.length;for(h=0;h<f;h++){var g=a.charCodeAt(h),
i=null;g<128?d++:i=g>127&&g<2048?String.fromCharCode(g>>6|192)+String.fromCharCode(g&63|128):String.fromCharCode(g>>12|224)+String.fromCharCode(g>>6&63|128)+String.fromCharCode(g&63|128);i!==null&&(d>c&&(b+=a.substring(c,d)),b+=i,c=d=h+1)}d>c&&(b+=a.substring(c,a.length));return b};b.set_cookie=function(a,e,c,d){var f=new Date,d=d?b.parse_domain(document.location.hostname):"",a=a+"="+escape(e);f.setDate(f.getDate()+c);a+=c===null?"":";expires="+f.toGMTString();a+="; path=/";a+=d?";domain=."+d:"";
document.cookie=a};b.get_cookie=function(a){var b;if(document.cookie.length>0&&(document.cookie.match("^"+a+"=")?b=0:(b=document.cookie.search("; "+a+"="),b!=-1&&(b+=2)),b!=-1)){b=b+a.length+1;a=document.cookie.indexOf(";",b);if(a==-1)a=document.cookie.length;return unescape(document.cookie.substring(b,a))}return""};b.delete_cookie=function(a,e){b.set_cookie(a,"",-1,e)};b.parse_domain=function(a){return(a=a.match(/[a-z0-9][a-z0-9\-]+\.[a-z\.]{2,6}$/i))?a[0]:""};b.get_super=function(){var a=eval("("+
b.get_cookie(b.config.cookie_name)+")")||{},e;for(e in a)a.hasOwnProperty(e)&&(b.super_properties[e]=a[e]);return b.super_properties};b.load_super_once=function(){if(!A)try{b.get_super(),A=!0}catch(a){}};b.register_funnel=function(a,e){b.funnels[a]=e};b.track_predefined_funnels=function(a,e){var c,d;if(a&&b.funnels)for(c in b.funnels)if(b.funnels.hasOwnProperty(c))for(d=0;d<b.funnels[c].length;++d)b.funnels[c][d]&&b.funnels[c][d]==a&&b.track_funnel(c,d+1,a,e)};b.save_campaign_params=function(){b.campaign_params_saved=
b.campaign_params_saved||!1;if(b.config.store_google&&!b.campaign_params_saved){var a=["utm_source","utm_medium","utm_campaign","utm_content","utm_term"],e="",c={},d;for(d=0;d<a.length;d++)e=b.get_query_param(document.URL,a[d]),e.length&&(c[a[d]]=e);b.register_once(c);b.campaign_params_saved=!0}};b.save_search_keyword=function(a){var e="";a.search("https?://(.*)google.([^/?]*)")===0?e=b.get_query_param(a,"q"):a.search("https?://(.*)bing.com")===0?e=b.get_query_param(a,"q"):a.search("https?://(.*)yahoo.com")===
0?e=b.get_query_param(a,"p"):a.search("https?://(.*)duckduckgo.com")===0&&(e=b.get_query_param(a,"q"));e.length&&b.register({mp_keyword:e},"all")};b.get_pageview_info=function(){var a=document.referrer,b;b=navigator.userAgent;b=window.opera?"Opera":/chrom/i.test(b)?"Chrome":/msie/i.test(b)?"Internet Explorer":/AppleWebKit/.test(navigator.appVersion)?"Safari":/mozilla/i.test(b)&&!/compatible|webkit/i.test(b)?"Firefox":"";var c;c=navigator.userAgent;c=/Windows/i.test(c)?"Windows":/iPhone/.test(c)?"iPhone":
/Android/.test(c)?"Android":/Mac/i.test(c)?"Mac OS X":/X11/.test(c)||/Linux/.test(c)?"Linux":"";var d=document.location.href,f={};if(a.length)f.mp_referrer=a;if(b.length)f.mp_browser=b;if(c.length)f.mp_platform=c;if(d.length)f.mp_page=d;return f};b.clear_old_cookie=function(){b.delete_cookie(b.config.cookie_name,!1);b.set_cookie(b.config.cookie_name,b.json_encode(b.super_properties),7,!0)};b.set_config=function(a){for(var e in a)a.hasOwnProperty(e)&&(b.config[e]=a[e])};var C="https:"==document.location.protocol?
"https://":"http://";b.token=l;b.api_host=C+"api.mixpanel.com";b.callback_fn=m?m+".jsonp_callback":"mpmetrics.jsonp_callback";(b.token=="metrics-1"||Math.random()<0.3)&&b.track_pageview();document.readyState==="complete"?o():document.addEventListener?(document.addEventListener("DOMContentLoaded",o,!1),document.addEventListener("load",o,!1)):r(window,"onload",o);b._private={dom_loaded:function(a){if(typeof a!=="undefined")p=a;else return p},is_list:j,is_dom_query:t,parse_dom_query:u,to_array:q,get_elements_by_class_name:v,
get_element_by_id:w,register_event:r,register_link_tracking_event:z,prevent_default:x,process_dom_loaded_queue:o};return b};typeof mpq!="undefined"&&mpq&&mpq[0]&&mpq[0][0]=="init"&&function(l){l.metrics=new MixpanelLib(l[0][1],"mpq.metrics");l.push=function(j){if(j)if(typeof j=="function")j();else if(j.constructor==Array){var m=l.metrics[j[0]];typeof m=="function"&&m.apply(l.metrics,j.slice(1))}};var m;for(m=1;m<l.length;m++)l.push(l[m]);l.length=0}(mpq);
